"""TEHTEK — Finance Extended Models. New tables only."""
from datetime import datetime
from sqlalchemy import func, Boolean, Column, DateTime, Float, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.orm import relationship
from app.core.database import Base

class Location(Base):
    __tablename__ = "locations"
    id                      = Column(Integer, primary_key=True)
    company_id              = Column(Integer, ForeignKey("companies.id"), nullable=False)
    name                    = Column(String(150), nullable=False)
    type                    = Column(String(30),  nullable=False)
    address                 = Column(String(300), nullable=True)
    city                    = Column(String(100), nullable=False)
    country                 = Column(String(100), nullable=False, default="Cameroon")
    rent_monthly            = Column(Numeric(14,2), nullable=False, default=0)
    electricity_monthly     = Column(Numeric(14,2), nullable=False, default=0)
    water_monthly           = Column(Numeric(14,2), nullable=False, default=0)
    internet_monthly        = Column(Numeric(14,2), nullable=False, default=0)
    other_utilities_monthly = Column(Numeric(14,2), nullable=False, default=0)
    lease_start             = Column(DateTime, nullable=True)
    lease_end               = Column(DateTime, nullable=True)
    next_payment_due        = Column(DateTime, nullable=True)
    landlord_name           = Column(String(200), nullable=True)
    landlord_contact        = Column(String(100), nullable=True)
    notes                   = Column(Text, nullable=True)
    status                  = Column(String(30), nullable=False, default="active")
    currency                = Column(String(10),  nullable=False, default="XAF")
    created_at              = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at              = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    money_accounts = relationship("MoneyAccount", back_populates="location", lazy="select")

class MoneyAccount(Base):
    __tablename__ = "money_accounts"
    id              = Column(Integer, primary_key=True)
    company_id      = Column(Integer, ForeignKey("companies.id"), nullable=False)
    name            = Column(String(150), nullable=False)
    type            = Column(String(30),  nullable=False)
    currency        = Column(String(10),  nullable=False, default="XAF")
    opening_balance = Column(Numeric(16,2), nullable=False, default=0)
    current_balance = Column(Numeric(16,2), nullable=False, default=0)
    location_id     = Column(Integer, ForeignKey("locations.id"), nullable=True)
    is_active       = Column(Boolean, nullable=False, default=True)
    notes           = Column(Text, nullable=True)
    created_at      = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at      = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    location = relationship("Location", back_populates="money_accounts")

class IncomeRecord(Base):
    __tablename__ = "income"
    id               = Column(Integer, primary_key=True)
    company_id       = Column(Integer, ForeignKey("companies.id"), nullable=False)
    branch_id        = Column(Integer, ForeignKey("branches.id"),  nullable=True)
    income_number    = Column(String(30), unique=True, nullable=False)
    date             = Column(DateTime, nullable=False)
    description      = Column(Text, nullable=False)
    category         = Column(String(60), nullable=False)
    ref_model        = Column(String(50), nullable=True)
    ref_id           = Column(Integer,    nullable=True)
    ref_label        = Column(String(200), nullable=True)
    customer_id      = Column(Integer, ForeignKey("customers.id"), nullable=True)
    tracking_number  = Column(String(100), nullable=True)
    container_id     = Column(Integer, nullable=True)
    amount           = Column(Numeric(16,2), nullable=False)
    currency         = Column(String(10), nullable=False, default="XAF")
    exchange_rate    = Column(Numeric(12,6), nullable=False, default=1)
    amount_base      = Column(Numeric(16,2), nullable=False)
    payment_method   = Column(String(30), nullable=False, default="cash")
    money_account_id = Column(Integer, ForeignKey("money_accounts.id"), nullable=True)
    status           = Column(String(30), nullable=False, default="pending")
    notes            = Column(Text, nullable=True)
    receipt_url      = Column(String(500), nullable=True)
    created_by       = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at       = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at       = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    deleted_at       = Column(DateTime, nullable=True)

class FinanceExpense(Base):
    __tablename__ = "finance_expenses"
    id               = Column(Integer, primary_key=True)
    company_id       = Column(Integer, ForeignKey("companies.id"), nullable=False)
    branch_id        = Column(Integer, ForeignKey("branches.id"),  nullable=True)
    expense_number   = Column(String(30), unique=True, nullable=False)
    date             = Column(DateTime, nullable=False)
    description      = Column(Text, nullable=False)
    category         = Column(String(60), nullable=False)
    ref_model        = Column(String(50), nullable=False)
    ref_id           = Column(Integer,    nullable=True)
    ref_label        = Column(String(200), nullable=False)
    supplier_id      = Column(Integer, nullable=True)
    customer_id      = Column(Integer, ForeignKey("customers.id"), nullable=True)
    location_id      = Column(Integer, ForeignKey("locations.id"), nullable=True)
    amount           = Column(Numeric(16,2), nullable=False)
    currency         = Column(String(10), nullable=False, default="XAF")
    exchange_rate    = Column(Numeric(12,6), nullable=False, default=1)
    amount_base      = Column(Numeric(16,2), nullable=False)
    payment_method   = Column(String(30), nullable=True)
    money_account_id = Column(Integer, ForeignKey("money_accounts.id"), nullable=True)
    status           = Column(String(30), nullable=False, default="pending")
    receipt_url      = Column(String(500), nullable=True)
    notes            = Column(Text, nullable=True)
    created_by       = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by      = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at       = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at       = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    deleted_at       = Column(DateTime, nullable=True)

class Receivable(Base):
    __tablename__ = "receivables"
    id                = Column(Integer, primary_key=True)
    company_id        = Column(Integer, ForeignKey("companies.id"), nullable=False)
    receivable_number = Column(String(30), unique=True, nullable=False)
    client_name       = Column(String(200), nullable=False)
    client_id         = Column(Integer, ForeignKey("customers.id"), nullable=True)
    invoice_number    = Column(String(30),  nullable=True)
    ref_model         = Column(String(50),  nullable=False)
    ref_id            = Column(Integer,     nullable=True)
    ref_label         = Column(String(200), nullable=False)
    amount            = Column(Numeric(16,2), nullable=False)
    paid_amount       = Column(Numeric(16,2), nullable=False, default=0)
    balance_due       = Column(Numeric(16,2), nullable=False)
    currency          = Column(String(10), nullable=False, default="XAF")
    exchange_rate     = Column(Numeric(12,6), nullable=False, default=1)
    amount_base       = Column(Numeric(16,2), nullable=False)
    issue_date        = Column(DateTime, nullable=False)
    due_date          = Column(DateTime, nullable=False)
    status            = Column(String(30), nullable=False, default="draft")
    notes             = Column(Text, nullable=True)
    created_at        = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at        = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

class BudgetLine(Base):
    __tablename__ = "budget_lines"
    id            = Column(Integer, primary_key=True)
    company_id    = Column(Integer, ForeignKey("companies.id"), nullable=False)
    period_year   = Column(Integer, nullable=False)
    period_month  = Column(Integer, nullable=True)
    category      = Column(String(60),  nullable=False)
    label         = Column(String(150), nullable=False)
    budget_amount = Column(Numeric(14,2), nullable=False)
    spent_amount  = Column(Numeric(14,2), nullable=False, default=0)
    income_amount = Column(Numeric(14,2), nullable=False, default=0)
    variance      = Column(Numeric(14,2), nullable=False, default=0)
    variance_pct  = Column(Numeric(8,4),  nullable=False, default=0)
    currency      = Column(String(10), nullable=False, default="XAF")
    notes         = Column(Text, nullable=True)
    created_at    = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at    = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

# ── Append to app/modules/finance/extended_models.py ─────────────────────────

